name: Main

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        compiler:
          - clang-13
          - clang-14
          - clang-15
          - gcc-10
          - gcc-11
          - gcc-12
          - gcc-13
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"
    - name: Build defines.json
      run: rake defines.json
      env:
        CC: ${{ matrix.compiler }}
    - uses: actions/upload-artifact@v4
      with:
        name: defines-${{ matrix.compiler }}.json
        path: defines.json
