name: Main

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        target:
          - { os: ubuntu-latest, cc: clang-13 }
          - { os: ubuntu-latest, cc: clang-14 }
          - { os: ubuntu-latest, cc: clang-15 }
          - { os: ubuntu-latest, cc: gcc-10 }
          - { os: ubuntu-latest, cc: gcc-11 }
          - { os: ubuntu-latest, cc: gcc-12 }
          - { os: ubuntu-latest, cc: gcc-13 }
          - { os: windows-latest, cc: msvc-13 }
          - { os: windows-latest, cc: msvc-15 }
          - { os: windows-latest, cc: msvc-17 }
          - { os: windows-latest, cc: msvc-19 }
          - { os: macos-latest, cc: gcc-11 }
          - { os: macos-latest, cc: gcc-12 }
          - { os: macos-latest, cc: gcc-13 }
    runs-on: ${{ matrix.target.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Run cmake
      run: cmake . -DCMAKE_C_COMPILER=${{ matrix.target.cc }}
      env:
        CC: ${{ matrix.target.cc }}
    - name: Build defines.json
      run: ruby bin/defines.rb
    - uses: actions/upload-artifact@v4
      with:
        name: defines-${{ matrix.target.os }}-${{ matrix.target.cc }}
        path: defines.json
  group:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v4
      with:
        pattern: defines-*
    - name: Build grouped.json
      run: ruby bin/grouped.rb
    - name: Upload grouped.json
      uses: actions/upload-artifact@v4
      with:
        name: grouped.json
        path: grouped.json
