name: Main

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        target:
          - { os: ubuntu-latest, cc: clang-13 }
          - { os: ubuntu-latest, cc: clang-14 }
          - { os: ubuntu-latest, cc: clang-15 }
          - { os: ubuntu-latest, cc: gcc-10 }
          - { os: ubuntu-latest, cc: gcc-11 }
          - { os: ubuntu-latest, cc: gcc-12 }
          - { os: ubuntu-latest, cc: gcc-13 }
    runs-on: ${{ matrix.target.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"
    - name: Build defines.json
      run: rake defines.json
      env:
        CC: ${{ matrix.target.cc }}
    - uses: actions/upload-artifact@v4
      with:
        name: defines-${{ matrix.target.cc }}.json
        path: defines.json
