name: Main

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  autoconf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run autoconf
      run: autoconf
    - name: Bundle configure
      run: tar -cvf configure.tar configure
    - name: Upload configure.tar
      uses: actions/upload-artifact@v4
      with:
        name: configure.tar
        path: configure.tar
  tests:
    needs: autoconf
    strategy:
      matrix:
        target:
          - { os: ubuntu-latest, cc: clang-13 }
          - { os: ubuntu-latest, cc: clang-14 }
          - { os: ubuntu-latest, cc: clang-15 }
          - { os: ubuntu-latest, cc: gcc-10 }
          - { os: ubuntu-latest, cc: gcc-11 }
          - { os: ubuntu-latest, cc: gcc-12 }
          - { os: ubuntu-latest, cc: gcc-13 }
          - { os: windows-latest, cc: msvc-19 }
    runs-on: ${{ matrix.target.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Download configure.tar
      uses: actions/download-artifact@v4
      with:
        name: configure.tar
    - name: Unbundle configure
      run: tar -xvf configure.tar
    - name: Run configure
      run: ./configure
      env:
        CC: ${{ matrix.target.cc }}
    - run: ls -R
    - name: Build defines.json
      run: ruby bin/defines.rb
    - uses: actions/upload-artifact@v4
      with:
        name: defines-${{ matrix.target.os }}-${{ matrix.target.cc }}
        path: defines.json
  group:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v4
      with:
        pattern: defines-*
    - name: Build grouped.json
      run: ruby bin/grouped.rb
    - name: Upload grouped.json
      uses: actions/upload-artifact@v4
      with:
        name: grouped.json
        path: grouped.json
